AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
  TargetRubyVersion: 2.7

  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'feature', 'resource', 'desc', 'task']

Style/Documentation:
  Enabled: false
