version: '3.7'

services:
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - postgres
    entrypoint: ./entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
    tty: true
    stdin_open: true

volumes:
    gems:
    rails_cache:
    postgres:
