version: '3.7'

services:
  web:
    build:
      context: .
    env_file:
      - .env
    entrypoint: ./entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
    tty: true
    stdin_open: true

volumes:
    gems:
    rails_cache:
